### ISSUE TITLE
TBI:  login feature in the Hotel Reservation Application

### ISSUE THREAD

**Issue by RAVIGANESHMBHAT** [dhirajwork/DevOps-Assignment#18]
**It is a must feature to include the login option in this application**

Please refer the below attached image for the design of sign in / sign up page.
<img width="860" alt="login_hotelReservationApp" src="https://user-images.githubusercontent.com/41186067/118236584-df187600-b4b3-11eb-9c80-9db8e967bc2a.PNG">

**Comment by dhirajwork** [comment]
https://github.com/dhirajwork/DevOps-Assignment/pull/19 Once this is merge we can close this issue.

**Comment by dhirajwork** [comment]
The PR is merged and tested. Closing this issue.
